name: actions

on: 
  push:

jobs:
  test-action:
    name: test actions
    runs-on: ubuntu-latest
    steps:
        - name: list files
          run: ls
        - name: checkout repo
        
        - name: Checkout
          uses: actions/checkout@v4.2.2
        - name: ls
          run: ls
        - name: hello world action
          id: hello-world-action
          uses: actions/hello-world-javascript-action@main
          with:
            who-to-greet: "Hamed"
        - name: time
          run: echo "'greering time:' ${{steps.hello-world-action.outputs.time}}"
        - name: docekr action
          uses: docekr://hello-world:latest
  
